-- The FDS authentication database intentionally contains only these two tables:
-- user accounts and browser/device sessions.

CREATE TYPE "Role" AS ENUM ('guest', 'member', 'admin');

CREATE TABLE "user" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "email" VARCHAR(255) NOT NULL,
    "password_hash" VARCHAR(255),
    -- Required by the current registration and Google OAuth interfaces.
    "name" VARCHAR(255) NOT NULL,
    "google_id" VARCHAR(255),
    "role" "Role" NOT NULL DEFAULT 'guest',
    "create_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "user_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "user_email_format_check"
      CHECK ("email" LIKE '%_@__%.__%'),
    CONSTRAINT "user_password_hash_length_check"
      CHECK ("password_hash" IS NULL OR char_length("password_hash") >= 60)
);

CREATE UNIQUE INDEX "user_email_key" ON "user"("email");
CREATE UNIQUE INDEX "user_google_id_key" ON "user"("google_id");

CREATE TABLE "session" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id" BIGINT,
    "session_token" VARCHAR(255) NOT NULL,
    "ip_address" VARCHAR(45),
    "user_address" TEXT NOT NULL,
    "expires_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "session_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "session_user_id_fkey"
      FOREIGN KEY ("user_id") REFERENCES "user"("id")
      ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE UNIQUE INDEX "session_session_token_key" ON "session"("session_token");
CREATE INDEX "session_user_id_idx" ON "session"("user_id");
CREATE INDEX "session_expires_at_idx" ON "session"("expires_at");

-- Keep the update timestamp accurate for Prisma and direct SQL updates alike.
CREATE OR REPLACE FUNCTION public.set_user_update_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.update_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$function$;

CREATE TRIGGER "user_set_update_at"
BEFORE UPDATE ON public."user"
FOR EACH ROW
EXECUTE FUNCTION public.set_user_update_at();

-- PostgreSQL has no native TTL column. Supabase's pg_cron runs this indexed
-- cleanup every minute, independently of whether an application request arrives.
CREATE OR REPLACE FUNCTION public.delete_expired_sessions()
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
  DELETE FROM public."session" WHERE "expires_at" <= CURRENT_TIMESTAMP;
END;
$function$;

CREATE EXTENSION IF NOT EXISTS pg_cron;

DO $cleanup$
DECLARE
  existing_job record;
BEGIN
  FOR existing_job IN
    SELECT jobid FROM cron.job WHERE jobname = 'delete_expired_sessions_every_minute'
  LOOP
    PERFORM cron.unschedule(existing_job.jobid);
  END LOOP;

  PERFORM cron.schedule(
    'delete_expired_sessions_every_minute',
    '* * * * *',
    'SELECT public.delete_expired_sessions();'
  );
END;
$cleanup$;
